name: flutter_package_integrator
description: A desktop app to automate Flutter package integration like google_maps_flutter.
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^6.1.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  path_provider: ^2.1.2
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true